# Generated by Django 5.1.6 on 2025-02-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0009_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication',
        ),
        migrations.AddField(
            model_name='book',
            name='publications',
            field=models.ManyToManyField(related_name='books', to='Book.publications'),
        ),
    ]
